/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DrawLayer: typeof import('./src/components/Pages/Index/DrawLayer.vue')['default']
    FeatureInfo: typeof import('./src/components/Pages/Index/FeatureInfo.vue')['default']
    MapBoxWrap: typeof import('./src/components/MapBoxWrap.vue')['default']
    MapHeader: typeof import('./src/components/Map/MapHeader.vue')['default']
    MapLayout: typeof import('./src/components/Map/MapLayout.vue')['default']
    MapLogo: typeof import('./src/components/Map/MapLogo.vue')['default']
    MapParkingSpotInfo: typeof import('./src/components/Map/MapParkingSpotInfo.vue')['default']
    ModalAbout: typeof import('./src/components/Modal/ModalAbout.vue')['default']
    ModalDataMultipleMarker: typeof import('./src/components/Modal/ModalDataMultipleMarker.vue')['default']
    ModalDrawDataUpload: typeof import('./src/components/Modal/ModalDrawDataUpload.vue')['default']
    ModalJoinUs: typeof import('./src/components/Modal/ModalJoinUs.vue')['default']
    ModalMapDraw: typeof import('./src/components/Modal/ModalMapDraw.vue')['default']
    ModalWeixinMiniApp: typeof import('./src/components/Modal/ModalWeixinMiniApp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TypeLayer: typeof import('./src/components/Pages/Index/TypeLayer.vue')['default']
    ViewFlightItem: typeof import('./src/components/ViewFlight/ViewFlightItem.vue')['default']
    ViewFlightPointCard: typeof import('./src/components/ViewFlight/ViewFlightPointCard.vue')['default']
  }
}
