[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max-old-space-size=32768"

[build]
  publish = "dist"
  command = "pnpm check && pnpm build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
