name: Data Sync

on:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches:
      - main

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Get source sha
        run: date +%Y-%m-%d > sha 

      - name: Update source sha
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update source sha"
          add: "sha"
